import { useEffect, useState } from 'react'
import { ArrowLeft, Plus, RefreshCw, Save, Trash2, Search, X } from 'lucide-react'
import { supabase } from './lib/supabase'

type ModuleKey='schools'|'products'|'packages'|'orders'|'payments'|'inventory'|'students'|'reports'|'catalog'|'coupons'

const META:Record<ModuleKey,{title:string;description:string}>={
 schools:{title:'Schools & Branches',description:'Manage schools, branches, contact details and active status.'},
 products:{title:'Products & Variants',description:'Manage individual uniform products, sizes, SKUs and prices.'},
 packages:{title:'Uniform Packages',description:'Build packages from your individual products.'},
 orders:{title:'Orders',description:'Review customer orders, totals and order status.'},
 payments:{title:'Payments',description:'Review payment transactions and payment status.'},
 inventory:{title:'Inventory',description:'Monitor stock by branch, product and variant.'},
 students:{title:'Parents & Students',description:'Manage student records and school relationships.'},
 reports:{title:'Reports',description:'View high-level sales, orders and inventory summaries.'},
 catalog:{title:'Catalog Rules',description:'Control branch-specific products, prices and visibility.'},
 coupons:{title:'Coupons',description:'Manage promotional discounts and branch availability.'}
}

export default function AdminWorkspace({module,onBack}:{module:ModuleKey;onBack:()=>void}){
 const m=META[module]
 return <div className="admin-workspace"><header className="admin-topbar"><div><button className="admin-back" onClick={onBack}><ArrowLeft size={17}/> Admin Dashboard</button><div className="workspace-heading"><span className="eyebrow">ADMINISTRATION</span><h1>{m.title}</h1><p>{m.description}</p></div></div></header><main className="workspace-body"><ModuleBody module={module}/></main></div>
}

function ModuleBody({module}:{module:ModuleKey}){
 switch(module){
  case 'schools': return <Schools/>
  case 'products': return <Products/>
  case 'packages': return <Packages/>
  case 'orders': return <SimpleTable title="Orders" table="orders" columns={['order_number','status','grand_total','currency','created_at']}/>
  case 'payments': return <SimpleTable title="Payments" table="payments" columns={['order_id','provider','amount','currency','status','paid_at','created_at']}/>
  case 'inventory': return <SimpleTable title="Inventory" table="branch_inventory" columns={['branch_id','product_id','variant_id','quantity_on_hand','reorder_level','updated_at']}/>
  case 'students': return <SimpleTable title="Parents & Students" table="students" columns={['student_code','full_name','class_name','section','gender','date_of_birth','status']}/>
  case 'reports': return <Reports/>
  case 'catalog': return <Catalog/>
  case 'coupons': return <Coupons/>
 }
}

function Panel({children}:{children:React.ReactNode}){return <section className="workspace-panel">{children}</section>}
function Toolbar({children,onRefresh}:{children:React.ReactNode;onRefresh:()=>void}){return <div className="workspace-toolbar"><div>{children}</div><button className="secondary-button" onClick={onRefresh}><RefreshCw size={15}/> Refresh</button></div>}
function Loading(){return <div className="workspace-empty">Loading...</div>}
function ErrorBox({text}:{text:string}){return text?<div className="workspace-error">{text}</div>:null}

function Schools(){
 const [schools,setSchools]=useState<any[]>([]),[branches,setBranches]=useState<any[]>([]),[editing,setEditing]=useState<any>(null),[branchEditing,setBranchEditing]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 const load=async()=>{if(!supabase)return;setLoading(true);const a=await supabase.from('schools').select('*').order('name');const b=await supabase.from('branches').select('*').order('name');setSchools(a.data??[]);setBranches(b.data??[]);setError(a.error?.message||b.error?.message||'');setLoading(false)}
 useEffect(()=>{void load()},[])
 const saveSchool=async()=>{if(!supabase||!editing)return;const payload={name:editing.name,code:editing.code,logo_url:editing.logo_url||null,status:editing.status};const r=editing.id?await supabase.from('schools').update(payload).eq('id',editing.id):await supabase.from('schools').insert(payload);if(r.error)setError(r.error.message);else{setEditing(null);await load()}}
 const saveBranch=async()=>{if(!supabase||!branchEditing)return;const payload={school_id:branchEditing.school_id,name:branchEditing.name,code:branchEditing.code,address_line1:branchEditing.address_line1||null,address_line2:branchEditing.address_line2||null,city:branchEditing.city||null,state:branchEditing.state||null,postal_code:branchEditing.postal_code||null,phone:branchEditing.phone||null,email:branchEditing.email||null,status:branchEditing.status};const r=branchEditing.id?await supabase.from('branches').update(payload).eq('id',branchEditing.id):await supabase.from('branches').insert(payload);if(r.error)setError(r.error.message);else{setBranchEditing(null);await load()}}
 return <><Toolbar onRefresh={load}><button className="primary-button" onClick={()=>setEditing({name:'',code:'',status:'active'})}><Plus size={15}/> Add School</button></Toolbar><ErrorBox text={error}/>{loading?<Loading/>:<><Panel><h2>Schools</h2><div className="workspace-table">{schools.map(x=><div className="workspace-row" key={x.id}><strong>{x.name}</strong><span>{x.code}</span><span>{x.status}</span><button onClick={()=>setEditing({...x})}>Edit</button></div>)}</div></Panel><Panel><div className="panel-heading"><h2>Branches</h2><button className="secondary-button" onClick={()=>setBranchEditing({school_id:schools[0]?.id||'',name:'',code:'',status:'active'})}><Plus size={15}/> Add Branch</button></div><div className="workspace-table">{branches.map(x=><div className="workspace-row" key={x.id}><strong>{x.name}</strong><span>{schools.find(s=>s.id===x.school_id)?.name||'—'}</span><span>{x.code}</span><button onClick={()=>setBranchEditing({...x})}>Edit</button></div>)}</div></Panel></>}{editing&&<EditModal title={editing.id?'Edit School':'Add School'} onClose={()=>setEditing(null)} onSave={saveSchool}><Field label="School Name" value={editing.name} onChange={v=>setEditing({...editing,name:v})}/><Field label="Code" value={editing.code} onChange={v=>setEditing({...editing,code:v})}/><Field label="Logo URL" value={editing.logo_url||''} onChange={v=>setEditing({...editing,logo_url:v})}/><Select label="Status" value={editing.status} options={['active','inactive','suspended']} onChange={v=>setEditing({...editing,status:v})}/></EditModal>}{branchEditing&&<EditModal title={branchEditing.id?'Edit Branch':'Add Branch'} onClose={()=>setBranchEditing(null)} onSave={saveBranch}><Select label="School" value={branchEditing.school_id} options={schools.map(x=>x.id)} labels={Object.fromEntries(schools.map(x=>[x.id,x.name]))} onChange={v=>setBranchEditing({...branchEditing,school_id:v})}/><Field label="Branch Name" value={branchEditing.name} onChange={v=>setBranchEditing({...branchEditing,name:v})}/><Field label="Code" value={branchEditing.code} onChange={v=>setBranchEditing({...branchEditing,code:v})}/><Field label="City" value={branchEditing.city||''} onChange={v=>setBranchEditing({...branchEditing,city:v})}/><Field label="State" value={branchEditing.state||''} onChange={v=>setBranchEditing({...branchEditing,state:v})}/><Field label="Phone" value={branchEditing.phone||''} onChange={v=>setBranchEditing({...branchEditing,phone:v})}/><Select label="Status" value={branchEditing.status} options={['active','inactive','suspended']} onChange={v=>setBranchEditing({...branchEditing,status:v})}/></EditModal>}</>
}

function Products(){
 const [rows,setRows]=useState<any[]>([]),[editing,setEditing]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[search,setSearch]=useState('')
 const load=async()=>{if(!supabase)return;setLoading(true);const r=await supabase.from('products').select('*').order('name');setRows(r.data??[]);setError(r.error?.message||'');setLoading(false)};useEffect(()=>{void load()},[])
 const save=async()=>{if(!supabase||!editing)return;const slug=(editing.slug||editing.name||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const p={name:editing.name,slug,description:editing.description||null,gender:editing.gender,image_url:editing.image_url||null,base_price:Number(editing.base_price||0),status:editing.status};const r=editing.id?await supabase.from('products').update(p).eq('id',editing.id):await supabase.from('products').insert(p);if(r.error)setError(r.error.message);else{setEditing(null);await load()}}
 const visible=rows.filter(x=>x.name.toLowerCase().includes(search.toLowerCase()))
 return <><Toolbar onRefresh={load}><div className="toolbar-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products"/></div><button className="primary-button" onClick={()=>setEditing({name:'',gender:'unisex',base_price:0,status:'active'})}><Plus size={15}/> Add Product</button></Toolbar><ErrorBox text={error}/>{loading?<Loading/>:<Panel><div className="workspace-table">{visible.map(x=><div className="workspace-row" key={x.id}><strong>{x.name}</strong><span>{x.gender}</span><span>₹{Number(x.base_price||0).toLocaleString('en-IN')}</span><span>{x.status}</span><button onClick={()=>setEditing({...x})}>Edit</button></div>)}</div></Panel>}{editing&&<EditModal title={editing.id?'Edit Product':'Add Product'} onClose={()=>setEditing(null)} onSave={save}><Field label="Name" value={editing.name} onChange={v=>setEditing({...editing,name:v})}/><Field label="Description" value={editing.description||''} onChange={v=>setEditing({...editing,description:v})} area/><Select label="Gender" value={editing.gender} options={['boys','girls','unisex']} onChange={v=>setEditing({...editing,gender:v})}/><Field label="Base Price" value={String(editing.base_price??0)} onChange={v=>setEditing({...editing,base_price:v})} type="number"/><Field label="Image URL" value={editing.image_url||''} onChange={v=>setEditing({...editing,image_url:v})}/><Select label="Status" value={editing.status} options={['active','inactive','suspended']} onChange={v=>setEditing({...editing,status:v})}/></EditModal>}</>
}

function Packages(){
 const [rows,setRows]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[editing,setEditing]=useState<any>(null),[error,setError]=useState('')
 const load=async()=>{if(!supabase)return;const [p,x]=await Promise.all([supabase.from('uniform_packages').select('*').order('name'),supabase.from('products').select('id,name').eq('status','active').order('name')]);setRows(p.data??[]);setProducts(x.data??[]);setError(p.error?.message||x.error?.message||'')};useEffect(()=>{void load()},[])
 const save=async()=>{if(!supabase||!editing)return;const slug=(editing.slug||editing.name||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const p={name:editing.name,slug,description:editing.description||null,gender:editing.gender,image_url:editing.image_url||null,base_price:Number(editing.base_price||0),status:editing.status};const r=editing.id?await supabase.from('uniform_packages').update(p).eq('id',editing.id):await supabase.from('uniform_packages').insert(p);if(r.error)setError(r.error.message);else{setEditing(null);await load()}}
 return <><Toolbar onRefresh={load}><button className="primary-button" onClick={()=>setEditing({name:'',gender:'unisex',base_price:0,status:'active'})}><Plus size={15}/> Add Package</button></Toolbar><ErrorBox text={error}/><Panel><div className="workspace-table">{rows.map(x=><div className="workspace-row" key={x.id}><strong>{x.name}</strong><span>{x.gender}</span><span>₹{Number(x.base_price||0).toLocaleString('en-IN')}</span><button onClick={()=>setEditing({...x})}>Edit</button></div>)}</div></Panel>{editing&&<EditModal title={editing.id?'Edit Package':'Add Package'} onClose={()=>setEditing(null)} onSave={save}><Field label="Name" value={editing.name} onChange={v=>setEditing({...editing,name:v})}/><Select label="Gender" value={editing.gender} options={['boys','girls','unisex']} onChange={v=>setEditing({...editing,gender:v})}/><Field label="Base Price" value={String(editing.base_price??0)} onChange={v=>setEditing({...editing,base_price:v})} type="number"/><Field label="Description" value={editing.description||''} onChange={v=>setEditing({...editing,description:v})} area/><Field label="Image URL" value={editing.image_url||''} onChange={v=>setEditing({...editing,image_url:v})}/><Select label="Status" value={editing.status} options={['active','inactive','suspended']} onChange={v=>setEditing({...editing,status:v})}/><p className="workspace-note">Package item builder can be added after the package itself is saved.</p></EditModal>}</>
}

function SimpleTable({title,table,columns}:{title:string;table:string;columns:string[]}){
 const [rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[search,setSearch]=useState('')
 const load=async()=>{if(!supabase)return;setLoading(true);const r=await (supabase.from(table as any) as any).select('*').order('created_at',{ascending:false}).limit(200);setRows(r.data??[]);setError(r.error?.message||'');setLoading(false)};useEffect(()=>{void load()},[])
 const filtered=rows.filter(r=>columns.some(c=>String(r[c]??'').toLowerCase().includes(search.toLowerCase())))
 return <><Toolbar onRefresh={load}><div className="toolbar-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={'Search '+title.toLowerCase()}/></div></Toolbar><ErrorBox text={error}/>{loading?<Loading/>:<Panel><div className="workspace-scroll"><table><thead><tr>{columns.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{filtered.map((r,i)=><tr key={r.id||i}>{columns.map(c=><td key={c}>{typeof r[c]==='object'?JSON.stringify(r[c]):String(r[c]??'—')}</td>)}</tr>)}</tbody></table></div></Panel>}</>
}

function Reports(){
 const [stats,setStats]=useState({orders:0,revenue:0,products:0,low:0}),[error,setError]=useState('')
 useEffect(()=>{async function load(){if(!supabase)return;const [o,p,i]=await Promise.all([supabase.from('orders').select('grand_total'),supabase.from('products').select('id',{count:'exact',head:true}),supabase.from('branch_inventory').select('quantity_on_hand,reorder_level')]);if(o.error||p.error||i.error)setError(o.error?.message||p.error?.message||i.error?.message||'Unable to load reports');setStats({orders:o.data?.length||0,revenue:(o.data||[]).reduce((a,x)=>a+Number(x.grand_total||0),0),products:p.count||0,low:(i.data||[]).filter(x=>Number(x.quantity_on_hand)<=Number(x.reorder_level)).length})}void load()},[])
 return <><ErrorBox text={error}/><div className="report-grid"><div><span>Orders</span><strong>{stats.orders}</strong></div><div><span>Revenue</span><strong>₹{stats.revenue.toLocaleString('en-IN')}</strong></div><div><span>Products</span><strong>{stats.products}</strong></div><div><span>Low Stock Items</span><strong>{stats.low}</strong></div></div><Panel><h2>Operational Summary</h2><p className="workspace-note">This report is live from the current Supabase data. Detailed date filters and exports can be added to the reporting workspace.</p></Panel></>
}

function Catalog(){
 const [rows,setRows]=useState<any[]>([]),[branches,setBranches]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[error,setError]=useState('')
 const load=async()=>{if(!supabase)return;const [r,b,p]=await Promise.all([supabase.from('branch_products').select('*'),supabase.from('branches').select('id,name'),supabase.from('products').select('id,name')]);setRows(r.data??[]);setBranches(b.data??[]);setProducts(p.data??[]);setError(r.error?.message||b.error?.message||p.error?.message||'')};useEffect(()=>{void load()},[])
 const toggle=async(x:any)=>{if(!supabase)return;const r=await supabase.from('branch_products').update({is_visible:!x.is_visible}).eq('branch_id',x.branch_id).eq('product_id',x.product_id);if(r.error)setError(r.error.message);else await load()}
 return <><Toolbar onRefresh={load}/><ErrorBox text={error}/><Panel><div className="workspace-table">{rows.map(x=><div className="workspace-row" key={x.branch_id+x.product_id}><strong>{branches.find(b=>b.id===x.branch_id)?.name||x.branch_id}</strong><span>{products.find(p=>p.id===x.product_id)?.name||x.product_id}</span><span>₹{Number(x.branch_price||0).toLocaleString('en-IN')}</span><span>{x.is_visible?'Visible':'Hidden'}</span><button onClick={()=>void toggle(x)}>{x.is_visible?'Hide':'Show'}</button></div>)}</div></Panel></>
}

function Coupons(){
 const [rows,setRows]=useState<any[]>([]),[editing,setEditing]=useState<any>(null),[error,setError]=useState('')
 const load=async()=>{if(!supabase)return;const r=await supabase.from('coupons').select('*').order('created_at',{ascending:false});setRows(r.data??[]);setError(r.error?.message||'')};useEffect(()=>{void load()},[])
 const save=async()=>{if(!supabase||!editing)return;const p={code:editing.code,description:editing.description||null,discount_type:editing.discount_type,discount_value:Number(editing.discount_value||0),starts_at:editing.starts_at||null,expires_at:editing.expires_at||null,usage_limit:editing.usage_limit?Number(editing.usage_limit):null,status:editing.status};const r=editing.id?await supabase.from('coupons').update(p).eq('id',editing.id):await supabase.from('coupons').insert(p);if(r.error)setError(r.error.message);else{setEditing(null);await load()}}
 return <><Toolbar onRefresh={load}><button className="primary-button" onClick={()=>setEditing({code:'',description:'',discount_type:'percent',discount_value:0,status:'active'})}><Plus size={15}/> Add Coupon</button></Toolbar><ErrorBox text={error}/><Panel><div className="workspace-table">{rows.map(x=><div className="workspace-row" key={x.id}><strong>{x.code}</strong><span>{x.discount_type}</span><span>{x.discount_value}</span><span>{x.status}</span><button onClick={()=>setEditing({...x})}>Edit</button></div>)}</div></Panel>{editing&&<EditModal title={editing.id?'Edit Coupon':'Add Coupon'} onClose={()=>setEditing(null)} onSave={save}><Field label="Code" value={editing.code} onChange={v=>setEditing({...editing,code:v})}/><Field label="Description" value={editing.description||''} onChange={v=>setEditing({...editing,description:v})} area/><Select label="Discount Type" value={editing.discount_type} options={['percent','fixed']} onChange={v=>setEditing({...editing,discount_type:v})}/><Field label="Discount Value" value={String(editing.discount_value)} onChange={v=>setEditing({...editing,discount_value:v})} type="number"/><Field label="Usage Limit" value={String(editing.usage_limit||'')} onChange={v=>setEditing({...editing,usage_limit:v})} type="number"/><Select label="Status" value={editing.status} options={['active','inactive','suspended']} onChange={v=>setEditing({...editing,status:v})}/></EditModal>}</>
}

function EditModal({title,onClose,onSave,children}:{title:string;onClose:()=>void;onSave:()=>void;children:React.ReactNode}){return <div className="workspace-modal"><div className="workspace-modal-card"><button className="workspace-close" onClick={onClose}><X size={18}/></button><h2>{title}</h2><div className="workspace-form">{children}</div><div className="workspace-modal-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" onClick={onSave}><Save size={15}/> Save</button></div></div></div>}
function Field({label,value,onChange,type='text',area=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;area?:boolean}){return <label className="workspace-field"><span>{label}</span>{area?<textarea value={value} onChange={e=>onChange(e.target.value)}/>:<input type={type} value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function Select({label,value,options,labels,onChange}:{label:string;value:string;options:string[];labels?:Record<string,string>;onChange:(v:string)=>void}){return <label className="workspace-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x} value={x}>{labels?.[x]||x}</option>)}</select></label>}
